language: cpp
compiler:
  - gcc
  #- clang
before_install :
   - sudo apt-get install libhdf5-serial-dev
   - sudo apt-get install python-numpy
   - wget http://sourceforge.net/projects/boost/files/boost/1.54.0/boost_1_54_0.tar.bz2
   - tar --bzip2 -xf boost_1_54_0.tar.bz2
   - cd boost_1_54_0
   - ./bootstrap.sh --help
   - sudo ./bootstrap.sh
   - sudo ./b2 install
   - cd ..


# Change this to your needs..
script: 
  - cmake . -DWITH_BOOST=TRUE -DWITH_HDF5=TRUE -DWITH_TRWS=TRUE  -DWITH_QPBO=TRUE -DWITH_MRF=TRUE  -DWITH_GCO=TRUE  -DWITH_CONICBUNDLE=TRUE  -DWITH_MAXFLOW=TRUE  -DWITH_MAXFLOW_IBFS=TRUE -DBUILD_PYTHON_WRAPPER=TRUE
  - make  externalLibs 
  - cmake . -DWITH_BOOST=TRUE -DWITH_HDF5=TRUE -DWITH_TRWS=TRUE  -DWITH_QPBO=TRUE -DWITH_MRF=TRUE  -DWITH_GCO=TRUE  -DWITH_CONICBUNDLE=TRUE  -DWITH_MAXFLOW=TRUE  -DWITH_MAXFLOW_IBFS=TRUE -DBUILD_PYTHON_WRAPPER=TRUE
  - make 
  - make test 
  - make test-python-wrapper
  - sudo make install

